# Generated by Django 4.2.1 on 2025-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_owner_question_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.IntegerField(default=0),
        ),
    ]
