# Generated by Django 4.2.1 on 2025-08-17 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 18, 19, 1, 870056), verbose_name='date published'),
        ),
    ]
