# Generated by Django 5.2.5 on 2025-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
